# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Food name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('allergen', models.CharField(max_length=100, verbose_name='Allergen')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
            ],
        ),
    ]
