# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_food_allergen'),
    ]

    operations = [
        migrations.CreateModel(
            name='vine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vine name')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
